### PR TITLE
Readability & minor error corrections

### PR DESCRIPTION
**Pull request by JamesRamm**
Hi
Thanks for the useful library. I hope you can accept these minor readability changes. It is all based on PEP8 using pylint, which also uncovered a few minor errors. 
The manual edits in this PR only cover the tuflow side of the lib (as that is what im interested in at the moment...). Automatic edits (just removing trailing whitespace) cover the whole lib...

### CODE REVIEW

**Comment by duncan-r** [comment]
Hi James,
Thank you for your contributions. I'm glad to hear you're finding the library useful and it can definitely benefit from some input on the tuflow side. I've been really busy with other things lately and have not been able to continue fixing it up, so there are many outstanding issues. It would be good to have some support.

The fixes to badly implemented calls to super() etc are great, thanks. I am happy to pull most of this down, have a proper look and get it merged in. 

My one request is for you to separate the autopep8 stuff into a separate pull request if you wouldn't mind? It obviously hits almost every file and I've got some work in the fmp packages that I'd like to get merged sometime soon and I'd prefer to get that done without a ton of conflicts.

Once you've done that I will pull the other commits in pretty quickly and then get the pep8 one done when I can.

Thanks.

**Comment by JamesRamm** [comment]
@duncan-r 
Sure, ill try to separate it out. The auto fixes may be muddled up a bit in some commits, but i should be able to separate out the bulk of it. (I shouldnt expect any conflicts anyway since the auto stuff is only whitespace removal).
I'll hopefully get round to that tomorrow....

**Comment by duncan-r** [comment]
Excellent, thanks. If it's going to be a big hassle for you and this request is all basically cosmetic changes. I can probably give it a go and try and pull it all in. I noticed that there were some code changes - lambda's on callbacks for instance - and wasn't quite sure where they started and the whitespace stuff ended.
It's obviously just a bit tricky for me to see exactly what's been changed everywhere when so many files have been hit :)

**Comment by JamesRamm** [comment]
@duncan-r 
Yup, ill try to break it down. 
lambdas on the callbacks was to resolve an error in that the callback may potentially be called before it has been set (which would throw an exception as `None` is not callable). Most likely, there is no situation in which this would occur, but it is not quite yet clear to me what should be considered public api & what isnt so I put them in to cover either a user calling them when they shouldnt, or a user not setting the callbacks if they are expected to. 

Ill take a look at the git history tomorrow and try to organize this into 2 PR's - whitespace/autopep8 changes and manual refactors

**Comment by duncan-r** [comment]
That would be great thanks. Yes the lambdas sound sensible.

I think quite a lot of consideration is still needed on the public/private and organisation of the API in general. 

As a little history...
This project started with pulling a few common bits of complicated code out of other software to improve maintainability. It was just some really simple parsers and interrogation functions  for FMP .dat files.
Then the same thing kind of happened for the tuflow files and it all grew a little bit _organically_ over time.
At some point I decided to try and organise it all a little and packaged things up a bit more cleanly and put a few tests in place. Having never built any kind of API before, it was a bit of a learning experience (continuing) and there are many, many things I would do differently second time around.
I put it up on github in the hope that  
1) It might make someone else's life a bit easier - no one really likes writing file reading functions
2) People might want to contribute a bit and take some of the load off.

It's still very beta because of a number of reasons. Mostly needing to really nail down the API and structure a bit, but also me finding time to work on it. I usually have a flurry of activity when we need a new feature for internal software and scripts.

I would genuinely be interested if you have any thoughts on the main design structures and wouldn't necessarily mind breaking a few things if it meant I could finally get it sorted and into a main release.

**Comment by duncan-r** [comment]
Is this pull request no longer valid and everything will be done in a different place now? It seems there are some conflicts between this request and the other one that I just merged in?

**Comment by JamesRamm** [comment]
@duncan-r yes this one is not valid anymore. Remaining changes from here I wanted to add will be in 1 or 2 more PR's

**Pull request closed without merging**
